-- Создание таблицы рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    mpa_rating_id INTEGER PRIMARY KEY,
    name          VARCHAR(10) NOT NULL
);

-- Создание таблицы жанров
CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER PRIMARY KEY,
    name     VARCHAR(50) NOT NULL
);

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(100) NOT NULL,
    login    VARCHAR(100) NOT NULL,
    name     VARCHAR(100),
    birthday DATE
);

-- Создание таблицы фильмов
CREATE TABLE IF NOT EXISTS films
(
    film_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(200),
    release_date  DATE,
    duration      INTEGER,
    mpa_rating_id INTEGER,
    FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings (mpa_rating_id)
);

-- Создание таблицы связи фильмов и жанров (многие ко многим)
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER,
    genre_id INTEGER,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE
);

-- Создание таблицы лайков (многие ко многим)
CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER,
    user_id INTEGER,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Создание таблицы дружбы между пользователями
CREATE TABLE IF NOT EXISTS friendships
(
    user_id   INTEGER,
    friend_id INTEGER,
    status    VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Заполнение таблиц данными по умолчанию
-- Заполнение таблиц данными по умолчанию (ИСПРАВЛЕННЫЙ ВАРИАНТ)
MERGE INTO mpa_ratings (mpa_rating_id, name) KEY (mpa_rating_id) VALUES (1, 'G'),
                                                                        (2, 'PG'),
                                                                        (3, 'PG-13'),
                                                                        (4, 'R'),
                                                                        (5, 'NC-17');

MERGE INTO genres (genre_id, name) KEY (genre_id) VALUES (1, 'Комедия'),
                                                         (2, 'Драма'),
                                                         (3, 'Мультфильм'),
                                                         (4, 'Триллер'),
                                                         (5, 'Документальный'),
                                                         (6, 'Боевик');